create table if not exists public.bible (
  id bigint generated by default as identity primary key,
  book text not null,
  chapter integer not null check (chapter > 0),
  verse integer not null check (verse > 0),
  text text not null,
  step integer not null check (step > 0),
  created_at timestamptz not null default now(),
  unique (book, chapter, verse)
);

create index if not exists bible_step_idx
  on public.bible (step, book, chapter, verse);

create index if not exists bible_reference_idx
  on public.bible (book, chapter, verse);

alter table public.bible enable row level security;

drop policy if exists "Anyone can read bible verses" on public.bible;

create policy "Anyone can read bible verses"
  on public.bible
  for select
  using (true);
